stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building..."
  only:
    - master

test:
  stage: test
  script:
    - echo "Testing..."
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  only:
    - master
